# Generated by Django 2.0.8 on 2018-08-14 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_middle_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='domain_url',
        ),
    ]
