# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-23 21:26
from __future__ import unicode_literals

from django.db import migrations

def type_migration(apps, schema):
    Result = apps.get_model("reports", "Result")

    Result.objects.filter(result_type__name='Outcome').update(type='Outcome')
    Result.objects.filter(result_type__name='Output').update(type='Output')
    Result.objects.filter(result_type__name='Activity').update(type='Activity')

class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_auto_20180823_2003'),
    ]

    operations = [
        migrations.RunPython(type_migration, migrations.RunPython.noop)
    ]
