# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2018-08-23 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_auto_20180823_2126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='result',
            name='result_type',
        ),
        migrations.AlterField(
            model_name='result',
            name='type',
            field=models.CharField(choices=[('Outcome', 'Outcome'), ('Output', 'Output'), ('Activity', 'Activity')], default='Output', max_length=10, verbose_name='Result Type'),
        ),
        migrations.DeleteModel(
            name='ResultType',
        ),
    ]
